name: Migrator

on:
  push:
    branches: [main]
    paths:
      - backend/internal/migrator/**
      - backend/internal/entities/**
      - backend/internal/migrations/**
  pull_request:
    branches: [main]
    paths:
      - backend/internal/migrator/**
      - backend/internal/entities/**
      - backend/internal/migrations/**

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
          cache-dependency-path: "backend/go.sum"

      - run: go mod download
        working-directory: backend

      - run: go run internal/migrator/main.go
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PATH_MIGRATION: "file://internal/migrations"
